# Generated by Django 3.2 on 2021-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='movie',
        ),
        migrations.AddField(
            model_name='planet',
            name='movie',
            field=models.ManyToManyField(related_name='planet_in_movie', to='planet_movies.Movie'),
        ),
    ]
